name: test1
on:
    push:
        branches:
        - main
jobs:
    job1:
        runs-on: ubutu-latest
        steps:
        - name: chekout code
          uses: actions/checkout@v2
        - name: print welcome message
          run: echo "welcome to test1 programm"